In [2]:
import plotly.express as px
import pandas as pd

df = pd.read_excel(
    "../data/resultat-ansokningsomgang-2024.xlsx",
    sheet_name="Tabell 3",
    skiprows=5,
)

# goal:
# Antal sökta utbildningar per kommun

df.head()

,Utbildningsområde,SUN5 inriktning,SUN5 inriktning namn,Utbildningsnamn,Beslut,Diarienummer,Flera kommuner,Antal kommuner,Län,Kommun,...,Sökta utbildningsomgångar,Beviljade utbildningsomgångar,Sökta platser per utbildningsomgång,Sökta platser totalt,Beviljade platser utbildningsomgång 1,Beviljade platser utbildningsomgång 2,Beviljade platser utbildningsomgång 3,Beviljade platser utbildningsomgång 4,Beviljade platser utbildningsomgång 5,Beviljade platser totalt
0,Data/IT,481ab,"Utbildningar till programmerare, spel",AI Programmer,Avslag,MYH 2024/3742,Nej,1,Västerbotten,Umeå,...,3,0,30,90,0,0,0,0,0,0
1,Data/IT,481ab,"Utbildningar till programmerare, spel","Forsbergs, Spelutvecklare – Game Programming",Avslag,MYH 2024/4174,Nej,1,Stockholm,Stockholm,...,3,0,20,60,0,0,0,0,0,0
2,Data/IT,481ab,"Utbildningar till programmerare, spel",Futuregames Game Programmer Specialization,Avslag,MYH 2024/3029,Ja,2,Flera kommuner,Flera kommuner,...,3,0,30,90,0,0,0,0,0,0
3,Data/IT,481ab,"Utbildningar till programmerare, spel",Game Programmer,Avslag,MYH 2024/3425,Nej,1,Blekinge,Karlshamn,...,3,0,25,75,0,0,0,0,0,0
4,Data/IT,481ab,"Utbildningar till programmerare, spel",Spelprogrammerare,Beviljad,MYH 2024/3852,Nej,1,Skåne,Malmö,...,4,3,35,140,35,35,35,0,0,105

In [3]:
df["Kommun"].value_counts()

Kommun
Flera kommuner    292
Stockholm         248
Göteborg          157
Malmö              86
Linköping          32
                 ...
Götene              1
Ronneby             1
Västervik           1
Hammarö             1
Leksand             1
Name: count, Length: 104, dtype: int64

In [4]:
px.bar(df["Kommun"].value_counts())

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'variable=count<br>Kommun=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'count',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': 'count',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['Flera kommuner', 'Stockholm', 'Göteborg', 'Malmö', 'Linköping',
                          'Solna', 'Jönköping', 'Örebro', 'Västerås', 'Helsingborg', 'Sundsvall',
                          'Skellefteå', 'Umeå', 'Botkyrka', 'Mölndal', 'Växjö', 'Uppsala', 'Lund',
                          'Borås', 'Norrköping', 'Södertälje', 'Trollhättan', 'Nyköping',
                          'Karlshamn', 'Piteå', 'Vänersborg', 'Nässjö', 'Habo', 'Varberg',
                          'Halmstad', 'Karlstad', 'Gävle', 'Hudiksvall', 'Örnsköldsvik',
                          'Karlskrona', 'Luleå', 'Borlänge', 'Arboga', 'Sigtuna', 'Hässleholm',
                          'Skövde', 'Kalmar', 'Eslöv', 'Filipstad', 'Härryda', 'Eskilstuna',
                          'Lidköping', 'Kristianstad', 'Nynäshamn', 'Boden', 'Uddevalla',
                          'Ljungby', 'Östersund', 'Härnösand', 'Olofström', 'Oskarshamn',
                          'Kramfors', 'Arvika', 'Skara', 'Värnamo', 'Staffanstorp', 'Ängelholm',
                          'Falun', 'Sandviken', 'Tibro', 'Norrtälje', 'Forshaga', 'Falkenberg',
                          'Nacka', 'Sunne', 'Båstad', 'Tranås', 'Krokom', 'Enköping', 'Älmhult',
                          'Vellinge', 'Trelleborg', 'Sollefteå', 'Upplands-Bro', 'Åre', 'Klippan',
                          'Håbo', 'Lindesberg', 'Eksjö', 'Haninge', 'Mörbylånga', 'Svedala',
                          'Kungsbacka', 'Sollentuna', 'Höör', 'Mariestad', 'Katrineholm', 'Osby',
                          'Mora', 'Markaryd', 'Hultsfred', 'Askersund', 'Motala', 'Kungälv',
                          'Götene', 'Ronneby', 'Västervik', 'Hammarö', 'Leksand'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': ('JAH4AJ0AVgAgAB8AFgAWABQAEgAQAA' ... 'ABAAEAAQABAAEAAQABAAEAAQABAA=='),
                    'dtype': 'i2'},
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'variable'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'Kommun'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'value'}}}
})

In [5]:
df.query("Utbildningsområde == 'Data/IT'")[
    "Kommun"].value_counts().reset_index().rename({"count": "Ansökta utbildningar"}, axis=1)

            Kommun  Ansökta utbildningar
0        Stockholm                    70
1   Flera kommuner                    58
2         Göteborg                    51
3            Malmö                    30
4            Solna                    14
5        Linköping                    10
6        Sundsvall                    10
7          Mölndal                     7
8           Örebro                     6
9         Västerås                     4
10            Umeå                     3
11     Helsingborg                     3
12           Växjö                     3
13        Halmstad                     2
14        Karlstad                     2
15       Karlshamn                     2
16           Borås                     2
17      Norrköping                     1
18     Trollhättan                     1
19       Jönköping                     1
20          Kalmar                     1
21         Värnamo                     1
22           Luleå                     1
23         Älmhult                     1
24        Botkyrka                     1
25         Varberg                     1
26      Skellefteå                     1
27           Gävle                     1
28          Arboga                     1

In [7]:
educational_area = "Data/IT"
df.query("Utbildningsområde == @educational_area")[
    "Kommun"
    ].value_counts().reset_index().rename({"count": "Ansökta utbildningar"}, axis=1)

            Kommun  Ansökta utbildningar
0        Stockholm                    70
1   Flera kommuner                    58
2         Göteborg                    51
3            Malmö                    30
4            Solna                    14
5        Linköping                    10
6        Sundsvall                    10
7          Mölndal                     7
8           Örebro                     6
9         Västerås                     4
10            Umeå                     3
11     Helsingborg                     3
12           Växjö                     3
13        Halmstad                     2
14        Karlstad                     2
15       Karlshamn                     2
16           Borås                     2
17      Norrköping                     1
18     Trollhättan                     1
19       Jönköping                     1
20          Kalmar                     1
21         Värnamo                     1
22           Luleå                     1
23         Älmhult                     1
24        Botkyrka                     1
25         Varberg                     1
26      Skellefteå                     1
27           Gävle                     1
28          Arboga                     1

To update the graph

- it requires a function that returns a dataframe and this function can be filtered
- this filtered datafram is placed into a funtion to return a figure

In [9]:
def filter_df_municipality(df, educational_area = "Data/IT"):
    return(
    df.query("Utbildningsområde == @educational_area")[
        "Kommun"
        ].value_counts().reset_index().rename({"count": "Ansökta utbildningar"}, axis=1))

df_municipality = filter_df_municipality(df)
df_municipality

            Kommun  Ansökta utbildningar
0        Stockholm                    70
1   Flera kommuner                    58
2         Göteborg                    51
3            Malmö                    30
4            Solna                    14
5        Linköping                    10
6        Sundsvall                    10
7          Mölndal                     7
8           Örebro                     6
9         Västerås                     4
10            Umeå                     3
11     Helsingborg                     3
12           Växjö                     3
13        Halmstad                     2
14        Karlstad                     2
15       Karlshamn                     2
16           Borås                     2
17      Norrköping                     1
18     Trollhättan                     1
19       Jönköping                     1
20          Kalmar                     1
21         Värnamo                     1
22           Luleå                     1
23         Älmhult                     1
24        Botkyrka                     1
25         Varberg                     1
26      Skellefteå                     1
27           Gävle                     1
28          Arboga                     1

In [11]:
px.bar(df_municipality, y="Kommun", x= "Ansökta utbildningar")

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'Ansökta utbildningar=%{x}<br>Kommun=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'h',
              'showlegend': False,
              'textposition': 'auto',
              'type': 'bar',
              'x': {'bdata': 'RjozHg4KCgcGBAMDAwICAgIBAQEBAQEBAQEBAQE=', 'dtype': 'i1'},
              'xaxis': 'x',
              'y': array(['Stockholm', 'Flera kommuner', 'Göteborg', 'Malmö', 'Solna',
                          'Linköping', 'Sundsvall', 'Mölndal', 'Örebro', 'Västerås', 'Umeå',
                          'Helsingborg', 'Växjö', 'Halmstad', 'Karlstad', 'Karlshamn', 'Borås',
                          'Norrköping', 'Trollhättan', 'Jönköping', 'Kalmar', 'Värnamo', 'Luleå',
                          'Älmhult', 'Botkyrka', 'Varberg', 'Skellefteå', 'Gävle', 'Arboga'],
                         dtype=object),
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'Ansökta utbildningar'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'Kommun'}}}
})

In [13]:
def create_municipality_bar(df, **options):
    df["Ansökta_label"] = df["Ansökta utbildningar"].apply(
        lambda row: " " * 2 + f"{row}" + " " * 2
    )

    fig = px.bar(
        df,
        y="Kommun",
        x="Ansökta utbildningar",
        text="Ansökta_label",
    )
    fig.update_layout(
        plot_bgcolor="white",
        margin=dict(t=0, l=40, r=30, b=50),
        yaxis=dict(
            autorange="reversed",
            ticklabelposition="outside left",
            showline=True,
            linecolor="lightgray",
            title=dict(text=f"<b>{options.get('ylabel')}</b>"),
        ),
        xaxis=dict(
            linecolor="lightgray",
            showticklabels=False,
            title=f"<b>{options.get('xlabel')}</b>",
        ),
    )

    fig.update_traces(
        textposition="outside",
        hovertemplate="<b>%{y}</b><br>Ansökta utbildningar: %{x}",
    )

    return fig

create_municipality_bar(df_municipality, xlabel="# ANSÖKTA UTBILDNINGAR", ylabel = "Kommun")

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': '<b>%{y}</b><br>Ansökta utbildningar: %{x}',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'h',
              'showlegend': False,
              'text': array(['  70  ', '  58  ', '  51  ', '  30  ', '  14  ', '  10  ', '  10  ',
                             '  7  ', '  6  ', '  4  ', '  3  ', '  3  ', '  3  ', '  2  ', '  2  ',
                             '  2  ', '  2  ', '  1  ', '  1  ', '  1  ', '  1  ', '  1  ', '  1  ',
                             '  1  ', '  1  ', '  1  ', '  1  ', '  1  ', '  1  '], dtype=object),
              'textposition': 'outside',
              'type': 'bar',
              'x': {'bdata': 'RjozHg4KCgcGBAMDAwICAgIBAQEBAQEBAQEBAQE=', 'dtype': 'i1'},
              'xaxis': 'x',
              'y': array(['Stockholm', 'Flera kommuner', 'Göteborg', 'Malmö', 'Solna',
                          'Linköping', 'Sundsvall', 'Mölndal', 'Örebro', 'Västerås', 'Umeå',
                          'Helsingborg', 'Växjö', 'Halmstad', 'Karlstad', 'Karlshamn', 'Borås',
                          'Norrköping', 'Trollhättan', 'Jönköping', 'Kalmar', 'Värnamo', 'Luleå',
                          'Älmhult', 'Botkyrka', 'Varberg', 'Skellefteå', 'Gävle', 'Arboga'],
                         dtype=object),
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'tracegroupgap': 0},
               'margin': {'b': 50, 'l': 40, 'r': 30, 't': 0},
               'plot_bgcolor': 'white',
               'template': '...',
               'xaxis': {'anchor': 'y',
                         'domain': [0.0, 1.0],
                         'linecolor': 'lightgray',
                         'showticklabels': False,
                         'title': {'text': '<b># ANSÖKTA UTBILDNINGAR</b>'}},
               'yaxis': {'anchor': 'x',
                         'autorange': 'reversed',
                         'domain': [0.0, 1.0],
                         'linecolor': 'lightgray',
                         'showline': True,
                         'ticklabelposition': 'outside left',
                         'title': {'text': '<b>Kommun</b>'}}}
})