# `Matplotlib annotations`

In [2]:
import pandas as pd
import duckdb

df = pd.read_csv("data/1900-census-immigrant-pop-metro.csv")

df.head()

,City,State,Error,Total foreign born,Africa,"Asia (except China, Japan, and India)",Atlantic Islands,Australia,Austria,Belgium,...,Scotland,South America,Spain,Sweden,Switzerland,Turkey,Wales,West Indies (except Cuba and Puerto Rico),Other countries,Born at sea
0,Akron,Ohio,0,"7,127",4.0,NaN,NaN,1,190,9,...,187,1.0,2,200,258,NaN,226,8,NaN,6.0
1,Albany,New York,55,"17,718",3.0,39.0,4,13,106,13,...,395,1.0,1,65,64,21,80,4,3.0,15.0
2,Allegheny,Pennsylvania,0,"30,216",4.0,5.0,2,8,"3,929",10,...,"1,183",2.0,2,186,488,4,798,4,3.0,25.0
3,Allentown,Pennsylvania,3,"2,991",NaN,1.0,NaN,2,337,2,...,66,1.0,NaN,5,26,3,40,2,3.0,1.0
4,Altoona,Pennsylvania,65,"3,301",2.0,7.0,NaN,NaN,57,2,...,98,2.0,1,32,55,25,23,1,8.0,4.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 50 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   City                                         161 non-null    object
 1   State                                        161 non-null    object
 2   Error                                        161 non-null    int64
 3   Total foreign born                           161 non-null    object
 4   Africa                                       120 non-null    float64
 5   Asia (except China, Japan, and India)        133 non-null    float64
 6   Atlantic Islands                             99 non-null     object
 7   Australia                                    136 non-null    object
 8   Austria                                      161 non-null    object
 9   Belgium                                      145 non-null    object
 10  Bohemia                                      144 non-null    object
 11  Canada (English)                             161 non-null    object
 12  Canada (French)                              160 non-null    object
 13  Central America                              98 non-null     float64
 14  China                                        156 non-null    object
 15  Cuba                                         124 non-null    object
 16  Denmark                                      157 non-null    object
 17  England                                      161 non-null    object
 18  Europe (not otherwise specified)             82 non-null     float64
 19  Finland                                      120 non-null    object
 20  France                                       161 non-null    object
 21  Germany                                      161 non-null    object
 22  Greece                                       131 non-null    object
 23  Holland                                      152 non-null    object
 24  Hungary                                      155 non-null    object
 25  India                                        117 non-null    float64
 26  Ireland                                      161 non-null    object
 27  Italy                                        161 non-null    object
 28  Japan                                        75 non-null     object
 29  Luxemburg                                    53 non-null     float64
 30  Mexico                                       111 non-null    object
 31  Norway                                       159 non-null    object
 32  Pacific Islands (except Phillipine Islands)  85 non-null     float64
 33  Poland (Austrian)                            126 non-null    object
 34  Poland (German)                              133 non-null    object
 35  Poland (Russian)                             159 non-null    object
 36  Poland (unknown)                             148 non-null    object
 37  Portugal                                     85 non-null     object
 38  Roumania                                     102 non-null    object
 39  Russia                                       161 non-null    object
 40  Scotland                                     161 non-null    object
 41  South America                                135 non-null    float64
 42  Spain                                        124 non-null    object
 43  Sweden                                       161 non-null    object
 44  Switzerland                                  160 non-null    object
 45  Turkey                                       132 non-null    object
 46  Wales                                        161 non-null    object
 47  West Indies (except Cuba and Puerto Rico)    135 non-null    object
 48  Other countries                              113 non-null    float64
 49  Born at sea                                  160 non-null    float64
dtypes: float64(10), int64(1), object(39)
memory usage: 63.0+ KB

In [4]:
df["Total foreign born"].iloc[0]

'7,127'

In [11]:
df_nordic = df[["Sweden","Norway","Finland", "Denmark", "Total foreign born"]]
df_nordic.head()

  Sweden Norway Finland Denmark Total foreign born
0    200     59       1     105              7,127
1     65     12       3      21             17,718
2    186      9       5      15             30,216
3      5      2     NaN       5              2,991
4     32      4       3       5              3,301

In [12]:
df_nordic["Total foreign born"].str.replace(",", "")

0       7127
1      17718
2      30216
3       2991
4       3301
       ...
156    12518
157    37652
158    14634
159     1304
160    12207
Name: Total foreign born, Length: 161, dtype: object

In [18]:
columns = ["Sweden","Norway","Finland", "Denmark", "Total foreign born"]

df_nordic = df[columns]
df_nordic.head()

  Sweden Norway Finland Denmark Total foreign born
0    200     59       1     105              7,127
1     65     12       3      21             17,718
2    186      9       5      15             30,216
3      5      2     NaN       5              2,991
4     32      4       3       5              3,301

In [21]:
df_nordic.fillna("0")

    Sweden Norway Finland Denmark Total foreign born
0      200     59       1     105               7127
1       65     12       3      21              17718
2      186      9       5      15              30216
3        5      2       0       5               2991
4       32      4       3       5               3301
..     ...    ...     ...     ...                ...
156     45      2      52       3              12518
157   7542    269    1143     153              37652
158    289     46       6      81              14634
159     10      1       0       0               1304
160    343     14      28      27              12207

[161 rows x 5 columns]

In [25]:
for column in columns:
    df[column] = df_nordic[column].str.replace(",", "").astype(int)

df_nordic

AttributeError: Can only use .str accessor with string values!

In [ ]:
duckdb.query("""
    WITH nordic AS (
        FROM df
            SELECT)
                state,
                SUM("")

 """)